### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by Aabaddon** [AzureDoom/customportalapi-reforged#1]
does this mod work by itself? like, could i add something in a config file to change what is needed to open the nether portal?

**Comment by AzureDoom** [comment]
No, this would only work when used in a mod. The only thing I know would be less mod-free is https://www.curseforge.com/minecraft/mc-mods/datapack-portals for the Fabric version.

**Comment by Aabaddon** [comment]
i cri, but thanks for answering
