### ISSUE TITLE
Portals do not spawn on roof

### ISSUE THREAD

**Issue by The-Architects727** [AzureDoom/customportalapi-reforged#10]
Hello, I am currently using this mod with forge 1.20.1-47.2.0
And I am using it with the Ecospherical expansion along with the Ecospherical Dimensions datapack. But when I have a flat portal that is created above y=64 in the overworld, and is set to link to the asthenospherical dimension.
The portal does not spawn and the player is always teleported to their exact coordinates in the corresponding dimension. Which is usually above the logical heightof 96 and always above the build height of 63. The min height is -64.
If the portal is placed below y=64 in the overworld to start with, The portal functions as it should. Only above the build height in the destination dimension does the portal not work.

**Comment by AzureDoom** [comment]
A fix for this in testing, if found to be fixed, 1.20.1, 1.20.4, and 1.20.6 will get this fix. It will be part of 1.21 when it releases.

**Comment by AzureDoom** [comment]
Resolved of the latest update for each version now!
