### ISSUE TITLE
Maven SSL Certificate Expired

### ISSUE THREAD

**Issue by AnonymousHacker1279** [AzureDoom/customportalapi-reforged#12]
The SSL certificate for the `libs.azuredoom.com` maven seems to be expired as of today. Gradle will refuse to resolve dependencies from it in the meantime.

![image](https://github.com/AzureDoom/customportalapi-reforged/assets/48810167/73ebbb30-8f4a-4545-be42-10079897ac32)

![image](https://github.com/AzureDoom/customportalapi-reforged/assets/48810167/7f15e4bf-8cdc-47a8-9190-6087cdafebea)

**Comment by AzureDoom** [comment]
Please try clearing your cache and trying it now!

**Comment by AzureDoom** [comment]
Getting reports of AzureLibs users having the issue resolved for them now, closing for now!
