### ISSUE TITLE
"Mixing EntityMixin from cpapireforged.mixins.json into net.minecraft.world.entity.Entity"

### ISSUE THREAD

**Issue by Blucher555** [AzureDoom/customportalapi-reforged#14]
Tried to import this API into my (forge 1.20.1) project, but for some reason it keeps crashing on startup with this weird, long error
here's the log:
[latest.log](https://github.com/user-attachments/files/16790199/latest.log)

**Comment by Blucher555** [comment]
also should note that for some reason the 1.0.4 version for 1.20.1 isn't on the https://libs.azuredoom.com:4443/#/mods repo

**Comment by AzureDoom** [comment]
Have you ensured you have mixins enabled in your project.

**Comment by Blucher555** [comment]
@AzureDoom that was indeed the issue, though now that i got a portal to work in-game, it seems to be working completely fine, except for some reason getting into it (in both creative and survival) just doesn't show the portal screen overlay at all, even though looking at the code, it's supposed to be there

**Comment by AzureDoom** [comment]
Are you on 1.0.4? It's on the maven now https://libs.azuredoom.com:4443/#/mods/net/kyrptonaught/customportalapi/customportalapi-reforged1201/1.0.4 not sure you used cursed maven for it.

**Comment by AzureDoom** [comment]
Please reopen if you are still having this issue.
