### ISSUE TITLE
Can't seem to get it to work

### ISSUE THREAD

**Issue by Ralazar22** [AzureDoom/customportalapi-reforged#3]
Hello, I'm not really too well versed with this sort of thing, but I wanted to create a custom portal for a dimension in my modpack and decided to use this API to make it easier. I can't seem to get it to work however. Any insight into what's going on would be appreciated.

Here's the console log:
[yifhxyqcn5kca-console-log.txt](https://github.com/AzureDoom/customportalapi-reforged/files/13326982/yifhxyqcn5kca-console-log.txt)

**Comment by AzureDoom** [comment]
> fml.forgeVersion, 47.2.0

I only support up to 47.1.3 Forge and NeoForge. Newer versions past that are broken AF, and Forge no longer has a proper maintenance team behind it, so I have moved my mods to support NeoForge (the former maintenance team of Forge's fork). It offers support for up to Forge 47.1.3 for its 1.20.1 versions

**Comment by Ralazar22** [comment]
Thank you so much!

**Comment by Ralazar22** [comment]
Sorry for bothering you, but I've downgraded the forge version to 47.1.3 and I seem to still be getting the same error.

Here's the console log again if you want to have a look:
[aqusno2jqaurg-console-log.txt](https://github.com/AzureDoom/customportalapi-reforged/files/13327101/aqusno2jqaurg-console-log.txt)

Edit: Looking through, it seems that it attempts "Mixing EntityMixin from cpapireforged.mixins.json into net.minecraft.world.entity.Entity" and fails.

**Comment by Aabyonis** [comment]
> Sorry for bothering you, but I've downgraded the forge version to 47.1.3 and I seem to still be getting the same error.
> 
> Here's the console log again if you want to have a look: [aqusno2jqaurg-console-log.txt](https://github.com/AzureDoom/customportalapi-reforged/files/13327101/aqusno2jqaurg-console-log.txt)
> 
> Edit: Looking through, it seems that it attempts "Mixing EntityMixin from cpapireforged.mixins.json into net.minecraft.world.entity.Entity" and fails.

did you find a solution to this? im experiencing the same atm
