### ISSUE TITLE
Nether portals spawning on nether roof

### ISSUE THREAD

**Issue by rohbust** [AzureDoom/customportalapi-reforged#8]
Hi, I'm using version 1.0.2 on Forge 1.20.1, I registered a custom portal, but when I build, ignite and go through, it connects to the other side just fine, but spawns me on the roof of the nether, above the bedrock... 

Wondering if there's something I'm doing wrong or if theres something i can do, would greatly appreciate it :)

`    private void commonSetup(final FMLCommonSetupEvent event) {
        CustomPortalBuilder.beginPortal()
                .frameBlock(Blocks.CRYING_OBSIDIAN)
                .lightWithItem(ModItems.LIGHTERITEM.get())
                .destDimID(new ResourceLocation("the_nether"))
                .tintColor(45, 65, 101)
                .registerPortal();
}`

![2024-01-24_19 15 03](https://github.com/AzureDoom/customportalapi-reforged/assets/57041061/dff43aad-147b-446b-b2de-601536760742)
![2024-01-24_19 15 11](https://github.com/AzureDoom/customportalapi-reforged/assets/57041061/70727798-7e06-4714-b9b6-7660733a5ef7)

**Comment by AzureDoom** [comment]
Looks correct, but version of Forge are you using exactly? I built against NeoForge/Forge 47.1.3, Anything newer then that will be unsupported.

**Comment by AzureDoom** [comment]
Unable to recreate this in dev or prod.
